version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      #- aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 659597326903.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - echo npm install completed on `date`
      - npm run build
      #- echo npm run build completed on `date`
      #- TAG=$(date "+%Y%m%d%H%M%S")
      #- docker build -t 659597326903.dkr.ecr.ap-northeast-1.amazonaws.com/yuki:$TAG ./
      #- echo docker build completed on `date`
      #- docker push 659597326903.dkr.ecr.ap-northeast-1.amazonaws.com/yuki:$TAG
      #- echo docker push completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      #- ls -l ./dist/shop/
      - mv ./target/shop-api-0.0.1-SNAPSHOT.jar ./target/app.jar
      - chmod 777 ./appstart.sh
      #- printf '[{"name":"mynginx","imageUri":"%s"}]' 659597326903.dkr.ecr.ap-northeast-1.amazonaws.com/yuki:$TAG > imagedefinitions.json
      #- cat imagedefinitions.json
artifacts:
  files:
    - target/app.jar
    - batch/*
    - appstart.sh
    - appspec.yml

    #- dist/shop/*
    #- dist/shop/assets/*
    #- appspec.yml
    #- imagedefinitions.json
 
